### ISSUE TITLE
Defining blank rules on configuration files

### ISSUE THREAD

**Issue by Bernardo-MG** [weso/CWR-DataApi#133]
It should be posible to define blank rules in the configuration.

Something like this:

```
group:
  id: acknowledgement_transaction
  rules:
    - sequence:
      - record: acknowledgement
      - record: blank_20
```

Should become:

```
group:
  id: acknowledgement_transaction
  rules:
    - sequence:
      - record: acknowledgement
      - record: blank(20)
```

Where the number in parenthesis should be parsed, to indicate the size of the blank record.
